### ISSUE TITLE
Geonode server error page 

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#34]
When a broken volume URL is encountered, a Geonode error page occurs. However, this error page doesn't follow the same formatting as the rest of the project website although the links present work. The page also shows the user as logged out although logging in again returns a CSRF verification error message. Refreshing the page still shows the user logged out, but if I return to a valid website page, I'm still logged in. This particular issue though is for changing the the formatting of the Geonode error page to match the rest of the website.

<img width="1920" alt="Screen Shot 2022-02-20 at 16 50 20 PM" src="https://user-images.githubusercontent.com/20251272/154872563-05311700-9468-43a5-9432-10e094648b98.png">

**Comment by mradamcox** [comment]
Nice, I noticed this the other day too. Need to create a 500 template that inherits the current theme.

**Comment by mradamcox** [comment]
More difficult than I was expecting; I do have a `500.html` template already that is supposed to inherit from the base template with a generic error message. However, turns out that the theme content (style info, images) that is stored in the database doesn't get to the front-end for this template, because of the server error.

GeoNode seems to deal with this by duplicating the entire base, etc. template content into the [default 500.html file](https://github.com/GeoNode/geonode/blob/master/geonode/templates/500.html). Will have to think about this a little more... would love to avoid having to store themed style content in the database _and_ as inline style in the error page, just to get the latter to match...

**Comment by mradamcox** [comment]
Address this by adding a management command that mocks up a request to the homepage (in order to get a request object with the correct context) and then renders that request through a 500.html.template file, outputting the resulting content in a new 500.html file. This command can be run whenever changes to the theme are made (different header colors, etc.).
