### ISSUE TITLE
Unable to add georeferenced map to newly created web map

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#35]
I was creating a web map, but I noticed https://oldinsurancemaps.net/layers/geonode:eunice_la_1950_p3 can't be added. This missing OGC metadata problem referenced in the screenshot appears to be upstream since I found mention of this at https://github.com/GeoNode/geonode/issues/7306.

<img width="1920" alt="Screen Shot 2022-02-20 at 16 44 42 PM" src="https://user-images.githubusercontent.com/20251272/154872878-c2431377-e5b6-4a35-abf9-64d58d98ee64.png">

**Comment by mradamcox** [comment]
Ok, this is interesting because I encountered this during development, and found it was due to a comma `,` in the title of the layer. Hence, the current use of `-`: https://github.com/GeoNode/geonode/issues/8198. However, seems like something else is going on as well though. For now, I'll probably just rerun the most recent georeferencing session on this layer to see if that fixes the issue.

**Comment by mradamcox** [comment]
Also strange because going to the detail page for that layer and then clicking the Create a Map button from there seems to load the layer into the new map just fine. However, in the catalog the OGC metadata warning does show up just like in the screenshot above.

**Comment by mradamcox** [comment]
Re-running the session worked, now the layer can be added to a new web map.
