### ISSUE TITLE
[Bug] Can't click through coordinate display

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#43]
**Describe the problem**
When georeferencing, I can't single or double-click through the coordinate display on the left panel.

**Expected behavior**
A single click should create a GCP.  A double-click should zoom in inside the pane.

**Environment info:**
 - Device: Mac mini
 - Operating System: MacOS
 - Browser: Safari

**Comment by mradamcox** [comment]
I'm not sure that allowing a click through this display will be possible, because it's a separate div on top of the map element, assuming you are talking about this
![image](https://user-images.githubusercontent.com/10427268/156027755-242f580d-319b-43de-a108-290fe6c88f4c.png)
Possible solutions would be to
1. Change the cursor to a pointer (default) or red circle with a line through it, as opposed to the crosshair that is currently shown while picking a point
2. Add a light background to the div (a la the default OL controls) to set this spot visually apart from the rest of the map.

**Comment by BNAndras** [comment]
I think setting a div background would work. You may need to wrap it around the corner and turn over the +/- buttons (like an upside down L) so it doesn’t stick out weirdly.

**Comment by mradamcox** [comment]
Fixed with both ideas above.
