### ISSUE TITLE
[Bug] Layer download request size exception

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#46]
**Describe the problem**
Downloading GeoTIFF/GZIPs for a georeferenced layer results in an exception that too much data is being used. The limit is 585.94 MB, but the layers I tested are closer to 1GB+ each. Downloading the original dataset works, probably because the zip files are under this limit.  I think either this size limit needs to be increased or the option to download be disabled.

**Environment info:**
 - Device: Mac mini
 - Operating System: MacOS
 - Browser: Safari.

**Comment by mradamcox** [comment]
Thanks for pointing this out, it's actually a bit strange because on disk these geotiffs are under 50mb, so something more is going on during that download request. Really, the best way to use these layers locally (in QGIS or ArcGIS) just to connect to the Geoserver/Geonode instance through WMS, but that's more of an aside here. I'm more inclined to disable download for now (if that's possible) to address this in the short term.

**Comment by BNAndras** [comment]
I agree. It’s easier to disable the downloads since this likely isn’t a common scenario.
