### ISSUE TITLE
[Bug] Volume map doesn't zoom to georeferenced layers

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#54]
**Describe the problem**
The Baton Rouge 1885 volume map was zoomed to the already georeferenced layers. I georeferenced some sheets, and now the map viewer defaults to the Atlantic Ocean.  If I navigate to Baton Rouge, the georeferenced layers are still loaded. When I hit refresh, the map viewer goes back to the Atlantic Ocean

**Expected behavior**
Volume overview should stay centered and zoomed to georeferenced layers.

**Environment info:**
 - Device: Mac mini M1
 - Operating System: MacOS Monterey
 - Browser: Safari & Chrome

**Additional context**

<img width="1920" alt="Screen Shot 2022-03-05 at 11 34 36 AM" src="https://user-images.githubusercontent.com/20251272/156897678-8a2801a3-2ea4-4ee2-b642-a6b7d7348911.png">

**Comment by mradamcox** [comment]
Interesting, so I'm thinking the problem is that the extent of the one of the layers was miscalculated during its creation. So the automatic extent that is generated on the map load includes this very large, incorrect extent.

Aside from figuring out what caused the incorrect extent on the layer, a different fix would be to attach the region object to the Volume (the extent of Baton Rouge, e.g.) and use that for the map zoom/extent, instead of the aggregate of layer extents.

**Comment by mradamcox** [comment]
Turns out, the caching of the layer properties to the Volume must have happened at a point before the new layer had a properly set extent. Refreshing the lookup tables for this volume fixed the issue, and the map now zooms to the correct extent.

**Comment by BNAndras** [comment]
What if you attach the region object and then compare it to the aggregate of layer extents, using the smaller of the two? The aggregate works until there's an incorrect extent. At the same time, the region object is static and may not represent the historic area very well. For example, at Lake Charles the georeferencer viewer loads zoomed out, but the historic area is the middle third of the top third of the extent.

**Comment by mradamcox** [comment]
For now, I've added a repair button to the top of the map tools panel. This initiates a full refresh of the volume's lookups, which can take a few seconds, but will reliably get the current layer extents.
