### ISSUE TITLE
[Bug] Volume map repair tool won’t work

### ISSUE THREAD

**Issue by BNAndras** [mradamcox/loc-insurancemaps#67]
**Describe the problem**
I tried repairing the volume map at https://oldinsurancemaps.net/loc/sanborn03274_004/ but it will not zoom in to the four georeferenced layers. I’ve successfully repaired a few other volumes already.

**Additional context**
![AA043AB7-CD2F-47AA-B986-B3CFC6B4215F](https://user-images.githubusercontent.com/20251272/158298945-fd464d95-a932-462f-8117-a9ea43b4c282.png)

**Comment by BNAndras** [comment]
Looks like https://oldinsurancemaps.net/layers/geonode:bastrop_la_1907_p1_1 has a bad extent.

**Comment by mradamcox** [comment]
Ok, I see what's going on. Looks like this layer was trimmed down from a much wider image, which the (unfortunate) artifacts that appear sometimes in the trimming interface reveal:
![image](https://user-images.githubusercontent.com/10427268/158433738-be8317c9-2864-468d-baaa-a61795a3a684.png)
So, this repair button is working fine, it just that the extent of the layer isn't actually altered with the trim tool, because the layer itself is not altered through the trimming process.

So I'm going to close this ticket, but I could see a more general underlying issue of "update stored layer extent to match trim polygon" being something worthwhile tacking in the future.
